// Automatically generated by Model#
// Remove the above line before editing this file and it won't be changed by Model#

using System.Collections;
using System.IO;
using System.Xml;
using System;
using System.ComponentModel;
using org.pescuma.ModelSharp.Lib;
using System.Runtime.Serialization;
using System.Diagnostics;

namespace examples.@using
{

	[DataContract(Name = "Test2")]
	public class Test2 : BaseTest2
	{
		public Test2()
		: base()
		{
		}
		
		public Test2(Test2 other)
		: base(other)
		{
		}
		
	}
	
}
