// Automatically generated by Model#
// DO NOT EDIT THIS FILE

using org.pescuma.ModelSharp.Lib;
using System.Collections.Specialized;
using System;
using System.ComponentModel;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Diagnostics;

namespace examples.computeProperty
{

	[DataContract]
	[DebuggerDisplay("MyClass[X={X} Y={Y} Children={Children.Count}items P={P.Count}items]")]
	public abstract class BaseMyClass : INotifyPropertyChanging, INotifyChildPropertyChanging, INotifyPropertyChanged, INotifyChildPropertyChanged, IDeserializationCallback, ICloneable, ICopyable
	{
		#region Constructors
		
		protected BaseMyClass()
		{
			this.y = 2;
			this.children = new ObservableList<MyClass>();
			AddChildrenListListeners(this.children);
			this.p = new ObservableList<Point>();
			AddPListListeners(this.p);
		}
		
		protected BaseMyClass(BaseMyClass other)
		{
			this.x = other.X;
			this.y = other.Y;
			this.children = new ObservableList<MyClass>();
			AddChildrenListListeners(this.children);
			this.children.AddRange(other.Children);
			this.p = new ObservableList<Point>();
			AddPListListeners(this.p);
			this.p.AddRange(other.P);
		}
		
		#endregion Constructors
		
		#region Property X
		
		[DataMember(Name = "X", Order = 0, IsRequired = false)]
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double x;
		
		public double X
		{
			[DebuggerStepThrough]
			get {
				return GetX();
			}
			[DebuggerStepThrough]
			set {
				SetX(value);
			}
		}
		
		protected virtual double GetX()
		{
			return this.x;
		}
		
		protected virtual bool SetX(double x)
		{
			if (this.x == x)
				return false;
				
			NotifyPropertyChanging(() => X);
			
			this.x = x;
			
			NotifyPropertyChanged(() => X);
			
			return true;
		}
		
		#endregion Property X
		
		#region Property Y
		
		[DataMember(Name = "Y", Order = 1, IsRequired = false)]
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double y;
		
		public double Y
		{
			[DebuggerStepThrough]
			get {
				return GetY();
			}
			[DebuggerStepThrough]
			set {
				SetY(value);
			}
		}
		
		protected virtual double GetY()
		{
			return this.y;
		}
		
		protected virtual bool SetY(double y)
		{
			if (this.y == y)
				return false;
				
			NotifyPropertyChanging(() => Y);
			
			this.y = y;
			
			NotifyPropertyChanged(() => Y);
			
			return true;
		}
		
		#endregion Property Y
		
		#region Property Length
		
		public double Length
		{
			[DebuggerStepThrough]
			get {
				return ComputeLength();
			}
		}
		
		protected virtual double ComputeLength()
		{
			return Math.Sqrt(X * X + Y * Y);
		}
		
		#endregion Property Length
		
		#region Property Dummy
		
		public string Dummy
		{
			[DebuggerStepThrough]
			get {
				return ComputeDummy();
			}
		}
		
		protected abstract string ComputeDummy();
		
		#endregion Property Dummy
		
		#region Property DummyCached
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string dummyCachedCache;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool dummyCachedCacheValid;
		
		public string DummyCached
		{
			[DebuggerStepThrough]
			get {
				return ComputeAndCacheDummyCached();
			}
		}
		
		/// Do not call this method directly. Instead, call NotifyPropertyChanged(() => DummyCached)
		private void InvalidateDummyCachedCache()
		{
			dummyCachedCacheValid = false;
		}
		
		private string ComputeAndCacheDummyCached()
		{
			if (!dummyCachedCacheValid)
			{
				this.dummyCachedCache = ComputeDummyCached();
				this.dummyCachedCacheValid = true;
			}
			
			return this.dummyCachedCache;
		}
		
		protected abstract string ComputeDummyCached();
		
		#endregion Property DummyCached
		
		#region Property SquaredLength
		
		public double SquaredLength
		{
			[DebuggerStepThrough]
			get {
				return ComputeSquaredLength();
			}
		}
		
		protected abstract double ComputeSquaredLength();
		
		#endregion Property SquaredLength
		
		#region Property SquaredLengthCached
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double squaredLengthCachedCache;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool squaredLengthCachedCacheValid;
		
		public double SquaredLengthCached
		{
			[DebuggerStepThrough]
			get {
				return ComputeAndCacheSquaredLengthCached();
			}
		}
		
		/// Do not call this method directly. Instead, call NotifyPropertyChanged(() => SquaredLengthCached)
		private void InvalidateSquaredLengthCachedCache()
		{
			squaredLengthCachedCacheValid = false;
		}
		
		private double ComputeAndCacheSquaredLengthCached()
		{
			if (!squaredLengthCachedCacheValid)
			{
				this.squaredLengthCachedCache = ComputeSquaredLengthCached();
				this.squaredLengthCachedCacheValid = true;
			}
			
			return this.squaredLengthCachedCache;
		}
		
		protected abstract double ComputeSquaredLengthCached();
		
		#endregion Property SquaredLengthCached
		
		#region Property Children
		
		[DataMember(Name = "Children", Order = 2, IsRequired = false)]
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private readonly ObservableList<MyClass> children;
		
		public ObservableList<MyClass> Children
		{
			[DebuggerStepThrough]
			get {
				return GetChildren();
			}
		}
		
		protected virtual ObservableList<MyClass> GetChildren()
		{
			return this.children;
		}
		
		private void AddChildrenListListeners(ObservableList<MyClass> child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging += ChildrenListPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged += ChildrenListPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyCollectionChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.CollectionChanged += ChildrenListChangedEventHandler;
				
			foreach (var item in child)
				AddChildrenItemListeners(item);
		}
		
		private void ChildrenListPropertyChangingEventHandler(object sender, PropertyChangingEventArgs e)
		{
			if (e.PropertyName != ObservableList<MyClass>.PROPERTIES.ITEMS)
				return;
				
			NotifyPropertyChanging(() => Children);
		}
		
		private void ChildrenListPropertyChangedEventHandler(object sender, PropertyChangedEventArgs e)
		{
			if (e.PropertyName != ObservableList<MyClass>.PROPERTIES.ITEMS)
				return;
				
			NotifyPropertyChanged(() => Children);
		}
		
		private void ChildrenListChangedEventHandler(object sender, NotifyCollectionChangedEventArgs e)
		{
			switch (e.Action)
			{
				case NotifyCollectionChangedAction.Add:
				case NotifyCollectionChangedAction.Remove:
				case NotifyCollectionChangedAction.Replace:
				
					if ((e.OldItems == null || e.OldItems.Count == 0)
					        && (e.NewItems == null || e.NewItems.Count == 0))
						throw new InvalidOperationException();
						
					if (e.OldItems != null)
						foreach (var item in e.OldItems)
							RemoveChildrenItemListeners(item);
							
					if (e.NewItems != null)
						foreach (var item in e.NewItems)
							AddChildrenItemListeners(item);
							
					break;
				case NotifyCollectionChangedAction.Move:
					// Do nothing
					break;
				default:
					// NotifyCollectionChangedAction.Reset: The list should not fire this or
					// we can't control the items
					throw new InvalidOperationException();
			}
		}
		
		private void RemoveChildrenItemListeners(object child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging -= ChildrenItemPropertyChangingEventHandler;
				
			var notifyChildPropertyChanging = child as INotifyChildPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanging.ChildPropertyChanging -= ChildrenItemChildPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged -= ChildrenItemPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyChildPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.ChildPropertyChanged -= ChildrenItemChildPropertyChangedEventHandler;
		}
		
		private void AddChildrenItemListeners(object child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging += ChildrenItemPropertyChangingEventHandler;
				
			var notifyChildPropertyChanging = child as INotifyChildPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanging.ChildPropertyChanging += ChildrenItemChildPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged += ChildrenItemPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyChildPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.ChildPropertyChanged += ChildrenItemChildPropertyChangedEventHandler;
		}
		
		private void ChildrenItemPropertyChangingEventHandler(object sender, PropertyChangingEventArgs e)
		{
			NotifyChildPropertyChanging(() => Children, sender, e);
		}
		
		private void ChildrenItemChildPropertyChangingEventHandler(object sender, ChildPropertyChangingEventArgs e)
		{
			NotifyChildPropertyChanging(() => Children, sender, e);
		}
		
		private void ChildrenItemPropertyChangedEventHandler(object sender, PropertyChangedEventArgs e)
		{
			NotifyChildPropertyChanged(() => Children, sender, e);
		}
		
		private void ChildrenItemChildPropertyChangedEventHandler(object sender, ChildPropertyChangedEventArgs e)
		{
			NotifyChildPropertyChanged(() => Children, sender, e);
		}
		
		#endregion Property Children
		
		#region Property P
		
		[DataMember(Name = "P", Order = 3, IsRequired = false)]
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private readonly ObservableList<Point> p;
		
		public ObservableList<Point> P
		{
			[DebuggerStepThrough]
			get {
				return GetP();
			}
		}
		
		protected virtual ObservableList<Point> GetP()
		{
			return this.p;
		}
		
		private void AddPListListeners(ObservableList<Point> child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging += PListPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged += PListPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyCollectionChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.CollectionChanged += PListChangedEventHandler;
				
			foreach (var item in child)
				AddPItemListeners(item);
		}
		
		private void PListPropertyChangingEventHandler(object sender, PropertyChangingEventArgs e)
		{
			if (e.PropertyName != ObservableList<Point>.PROPERTIES.ITEMS)
				return;
				
			NotifyPropertyChanging(() => P);
		}
		
		private void PListPropertyChangedEventHandler(object sender, PropertyChangedEventArgs e)
		{
			if (e.PropertyName != ObservableList<Point>.PROPERTIES.ITEMS)
				return;
				
			NotifyPropertyChanged(() => P);
		}
		
		private void PListChangedEventHandler(object sender, NotifyCollectionChangedEventArgs e)
		{
			switch (e.Action)
			{
				case NotifyCollectionChangedAction.Add:
				case NotifyCollectionChangedAction.Remove:
				case NotifyCollectionChangedAction.Replace:
				
					if ((e.OldItems == null || e.OldItems.Count == 0)
					        && (e.NewItems == null || e.NewItems.Count == 0))
						throw new InvalidOperationException();
						
					if (e.OldItems != null)
						foreach (var item in e.OldItems)
							RemovePItemListeners(item);
							
					if (e.NewItems != null)
						foreach (var item in e.NewItems)
							AddPItemListeners(item);
							
					break;
				case NotifyCollectionChangedAction.Move:
					// Do nothing
					break;
				default:
					// NotifyCollectionChangedAction.Reset: The list should not fire this or
					// we can't control the items
					throw new InvalidOperationException();
			}
		}
		
		private void RemovePItemListeners(object child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging -= PItemPropertyChangingEventHandler;
				
			var notifyChildPropertyChanging = child as INotifyChildPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanging.ChildPropertyChanging -= PItemChildPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged -= PItemPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyChildPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.ChildPropertyChanged -= PItemChildPropertyChangedEventHandler;
		}
		
		private void AddPItemListeners(object child)
		{
			if (child == null)
				return;
				
			var notifyPropertyChanging = child as INotifyPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanging.PropertyChanging += PItemPropertyChangingEventHandler;
				
			var notifyChildPropertyChanging = child as INotifyChildPropertyChanging;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanging != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanging.ChildPropertyChanging += PItemChildPropertyChangingEventHandler;
				
			var notifyPropertyChanged = child as INotifyPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyPropertyChanged.PropertyChanged += PItemPropertyChangedEventHandler;
				
			var notifyChildPropertyChanged = child as INotifyChildPropertyChanged;
// ReSharper disable ConditionIsAlwaysTrueOrFalse
			if (notifyChildPropertyChanged != null)
// ReSharper restore ConditionIsAlwaysTrueOrFalse
				notifyChildPropertyChanged.ChildPropertyChanged += PItemChildPropertyChangedEventHandler;
		}
		
		private void PItemPropertyChangingEventHandler(object sender, PropertyChangingEventArgs e)
		{
			NotifyChildPropertyChanging(() => P, sender, e);
		}
		
		private void PItemChildPropertyChangingEventHandler(object sender, ChildPropertyChangingEventArgs e)
		{
			NotifyChildPropertyChanging(() => P, sender, e);
		}
		
		private void PItemPropertyChangedEventHandler(object sender, PropertyChangedEventArgs e)
		{
			NotifyChildPropertyChanged(() => P, sender, e);
		}
		
		private void PItemChildPropertyChangedEventHandler(object sender, ChildPropertyChangedEventArgs e)
		{
			NotifyChildPropertyChanged(() => P, sender, e);
		}
		
		#endregion Property P
		
		#region Property CompSub
		
		public double CompSub
		{
			[DebuggerStepThrough]
			get {
				return ComputeCompSub();
			}
		}
		
		protected abstract double ComputeCompSub();
		
		#endregion Property CompSub
		
		#region Property CompSubCached
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private double compSubCachedCache;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private bool compSubCachedCacheValid;
		
		public double CompSubCached
		{
			[DebuggerStepThrough]
			get {
				return ComputeAndCacheCompSubCached();
			}
		}
		
		/// Do not call this method directly. Instead, call NotifyPropertyChanged(() => CompSubCached)
		private void InvalidateCompSubCachedCache()
		{
			compSubCachedCacheValid = false;
		}
		
		private double ComputeAndCacheCompSubCached()
		{
			if (!compSubCachedCacheValid)
			{
				this.compSubCachedCache = ComputeCompSubCached();
				this.compSubCachedCacheValid = true;
			}
			
			return this.compSubCachedCache;
		}
		
		protected abstract double ComputeCompSubCached();
		
		#endregion Property CompSubCached
		
		#region Property Notification
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void NotifyPropertyChanging<T>(Expression<Func<T>> property)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			PropertyChangingEventHandler handler = PropertyChanging;
			if (handler != null)
				handler(this, new PropertyChangingEventArgs(propertyName));
				
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				NotifyPropertyChanging(() => Length);
				NotifyPropertyChanging(() => SquaredLength);
				NotifyPropertyChanging(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				NotifyPropertyChanging(() => Length);
				NotifyPropertyChanging(() => SquaredLength);
				NotifyPropertyChanging(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Children))
			{
				NotifyPropertyChanging(() => SquaredLength);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				NotifyPropertyChanging(() => SquaredLengthCached);
				NotifyPropertyChanging(() => CompSub);
				NotifyPropertyChanging(() => CompSubCached);
			}
		}
		
		public event ChildPropertyChangingEventHandler ChildPropertyChanging;
		
		protected virtual void NotifyChildPropertyChanging<T>(Expression<Func<T>> property, object sender, PropertyChangingEventArgs e)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			ChildPropertyChangingEventHandler handler = ChildPropertyChanging;
			if (handler != null)
				handler(sender, new ChildPropertyChangingEventArgs(this, propertyName, sender, e));
				
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				NotifyPropertyChanging(() => Length);
				NotifyPropertyChanging(() => SquaredLength);
				NotifyPropertyChanging(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				NotifyPropertyChanging(() => Length);
				NotifyPropertyChanging(() => SquaredLength);
				NotifyPropertyChanging(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Children))
			{
				NotifyPropertyChanging(() => SquaredLength);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				NotifyPropertyChanging(() => SquaredLengthCached);
				string path = (e is ChildPropertyChangingEventArgs ? ((ChildPropertyChangingEventArgs) e).FullPath : e.PropertyName);
				if (path == "X")
				{
					NotifyPropertyChanging(() => CompSub);
					NotifyPropertyChanging(() => CompSubCached);
				}
				else if (path == "Y")
				{
					NotifyPropertyChanging(() => CompSub);
					NotifyPropertyChanging(() => CompSubCached);
				}
			}
		}
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void NotifyPropertyChanged<T>(Expression<Func<T>> property)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				InvalidateSquaredLengthCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				InvalidateSquaredLengthCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				InvalidateSquaredLengthCachedCache();
				InvalidateCompSubCachedCache();
			}
			if (propertyName == ModelUtils.NameOfProperty(() => DummyCached))
			{
				InvalidateDummyCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => SquaredLengthCached))
			{
				InvalidateSquaredLengthCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => CompSubCached))
			{
				InvalidateCompSubCachedCache();
			}
			
			PropertyChangedEventHandler handler = PropertyChanged;
			if (handler != null)
				handler(this, new PropertyChangedEventArgs(propertyName));
				
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				NotifyPropertyChanged(() => Length);
				NotifyPropertyChanged(() => SquaredLength);
				NotifyPropertyChanged(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				NotifyPropertyChanged(() => Length);
				NotifyPropertyChanged(() => SquaredLength);
				NotifyPropertyChanged(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Children))
			{
				NotifyPropertyChanged(() => SquaredLength);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				NotifyPropertyChanged(() => SquaredLengthCached);
				NotifyPropertyChanged(() => CompSub);
				NotifyPropertyChanged(() => CompSubCached);
			}
		}
		
		public event ChildPropertyChangedEventHandler ChildPropertyChanged;
		
		protected virtual void NotifyChildPropertyChanged<T>(Expression<Func<T>> property, object sender, PropertyChangedEventArgs e)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				InvalidateSquaredLengthCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				InvalidateSquaredLengthCachedCache();
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				InvalidateSquaredLengthCachedCache();
				string path = (e is ChildPropertyChangedEventArgs ? ((ChildPropertyChangedEventArgs) e).FullPath : e.PropertyName);
				if (path == "X")
				{
					InvalidateCompSubCachedCache();
				}
				else if (path == "Y")
				{
					InvalidateCompSubCachedCache();
				}
			}
			
			ChildPropertyChangedEventHandler handler = ChildPropertyChanged;
			if (handler != null)
				handler(sender, new ChildPropertyChangedEventArgs(this, propertyName, sender, e));
				
			if (propertyName == ModelUtils.NameOfProperty(() => X))
			{
				NotifyPropertyChanged(() => Length);
				NotifyPropertyChanged(() => SquaredLength);
				NotifyPropertyChanged(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Y))
			{
				NotifyPropertyChanged(() => Length);
				NotifyPropertyChanged(() => SquaredLength);
				NotifyPropertyChanged(() => SquaredLengthCached);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => Children))
			{
				NotifyPropertyChanged(() => SquaredLength);
			}
			else if (propertyName == ModelUtils.NameOfProperty(() => P))
			{
				NotifyPropertyChanged(() => SquaredLengthCached);
				string path = (e is ChildPropertyChangedEventArgs ? ((ChildPropertyChangedEventArgs) e).FullPath : e.PropertyName);
				if (path == "X")
				{
					NotifyPropertyChanged(() => CompSub);
					NotifyPropertyChanged(() => CompSubCached);
				}
				else if (path == "Y")
				{
					NotifyPropertyChanged(() => CompSub);
					NotifyPropertyChanged(() => CompSubCached);
				}
			}
		}
		
		#endregion Property Notification
		
		#region CopyFrom
		
		void ICopyable.CopyFrom(object other)
		{
			CopyFrom((MyClass) other);
		}
		
		public virtual void CopyFrom(MyClass other)
		{
			X = other.X;
			Y = other.Y;
			Children.Clear();
			Children.AddRange(other.Children);
			P.Clear();
			P.AddRange(other.P);
		}
		
		#endregion CopyFrom
		
		#region Clone
		
#pragma warning disable 109
		public new MyClass Clone()
#pragma warning restore 109
		{
			return (MyClass) ((ICloneable) this).Clone();
		}
		
		object ICloneable.Clone()
		{
			return new MyClass((MyClass) this);
		}
		
		#endregion Clone
		
		#region Serialization
		
		void IDeserializationCallback.OnDeserialization(object sender)
		{
			AddChildrenListListeners(this.children);
			AddPListListeners(this.p);
		}
		
		#endregion Serialization
	}
	
}
