// Automatically generated by Model#
// DO NOT EDIT THIS FILE

using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics;
using System;

namespace examples.computeProperty
{

	public class MyImmutableClassBuilder
	{
		private double _x;
		private double _y = 2;
		private readonly List<MyClass> _children = new List<MyClass>();
		
		public virtual MyImmutableClassBuilder Set(MyImmutableClass other)
		{
			SetX(other.X);
			SetY(other.Y);
			ClearChildren();
			AddToChildren(other.Children);
			return this;
		}
		
		public virtual MyImmutableClassBuilder SetX(double x)
		{
			_x = x;
			return this;
		}
		
		public virtual MyImmutableClassBuilder SetY(double y)
		{
			_y = y;
			return this;
		}
		
		public virtual MyImmutableClassBuilder ClearChildren()
		{
			_children.Clear();
			return this;
		}
		public virtual MyImmutableClassBuilder AddToChildren(MyClass children)
		{
			_children.Add(children);
			return this;
		}
		public virtual MyImmutableClassBuilder AddToChildren(IEnumerable<MyClass> children)
		{
			_children.AddRange(children);
			return this;
		}
		
		public virtual MyImmutableClass Build()
		{
			return new MyImmutableClass(_x, _y, _children);
		}
	}
	
}
