// Automatically generated by Model#
// Remove the above line before editing this file and it won't be changed by Model#

using System.Runtime.Serialization;
using System.Diagnostics;
using System;

namespace examples.equals
{

	[DataContract(Name = "PointImmutable")]
	public class PointImmutable : BasePointImmutable
	{
		public PointImmutable(double? x, double y, PointImmutable a)
		: base(x, y, a)
		{
		}
		
		public PointImmutable(PointImmutable other)
		: base(other)
		{
		}
		
	}
	
}
