// Automatically generated by Model#
// DO NOT EDIT THIS FILE

using System;
using System.ComponentModel;
using System.Linq.Expressions;
using org.pescuma.ModelSharp.Lib;
using System.Runtime.Serialization;
using System.Diagnostics;

namespace examples.collectionReadOnly
{

	[DataContract]
	[DebuggerDisplay("House[Address={Address}]")]
	public abstract class BaseHouse : INotifyPropertyChanging, INotifyChildPropertyChanging, INotifyPropertyChanged, INotifyChildPropertyChanged, ICloneable, ICopyable
	{
		#region Constructors
		
		protected BaseHouse()
		{
		}
		
		protected BaseHouse(BaseHouse other)
		{
			this.address = other.Address;
		}
		
		#endregion Constructors
		
		#region Property Address
		
		[DataMember(Name = "Address", Order = 0, IsRequired = false)]
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string address;
		
		public string Address
		{
			[DebuggerStepThrough]
			get {
				return GetAddress();
			}
			[DebuggerStepThrough]
			set {
				SetAddress(value);
			}
		}
		
		protected virtual string GetAddress()
		{
			return this.address;
		}
		
		protected virtual bool SetAddress(string address)
		{
			if (this.address == address)
				return false;
				
			NotifyPropertyChanging(() => Address);
			
			this.address = address;
			
			NotifyPropertyChanged(() => Address);
			
			return true;
		}
		
		#endregion Property Address
		
		#region Property Notification
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void NotifyPropertyChanging<T>(Expression<Func<T>> property)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			PropertyChangingEventHandler handler = PropertyChanging;
			if (handler != null)
				handler(this, new PropertyChangingEventArgs(propertyName));
		}
		
		public event ChildPropertyChangingEventHandler ChildPropertyChanging;
		
		protected virtual void NotifyChildPropertyChanging<T>(Expression<Func<T>> property, object sender, PropertyChangingEventArgs e)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			ChildPropertyChangingEventHandler handler = ChildPropertyChanging;
			if (handler != null)
				handler(sender, new ChildPropertyChangingEventArgs(this, propertyName, sender, e));
		}
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void NotifyPropertyChanged<T>(Expression<Func<T>> property)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			PropertyChangedEventHandler handler = PropertyChanged;
			if (handler != null)
				handler(this, new PropertyChangedEventArgs(propertyName));
		}
		
		public event ChildPropertyChangedEventHandler ChildPropertyChanged;
		
		protected virtual void NotifyChildPropertyChanged<T>(Expression<Func<T>> property, object sender, PropertyChangedEventArgs e)
		{
			string propertyName = ModelUtils.NameOfProperty(property);
			
			ChildPropertyChangedEventHandler handler = ChildPropertyChanged;
			if (handler != null)
				handler(sender, new ChildPropertyChangedEventArgs(this, propertyName, sender, e));
		}
		
		#endregion Property Notification
		
		#region CopyFrom
		
		void ICopyable.CopyFrom(object other)
		{
			CopyFrom((House) other);
		}
		
		public virtual void CopyFrom(House other)
		{
			Address = other.Address;
		}
		
		#endregion CopyFrom
		
		#region Clone
		
#pragma warning disable 109
		public new House Clone()
#pragma warning restore 109
		{
			return (House) ((ICloneable) this).Clone();
		}
		
		object ICloneable.Clone()
		{
			return new House((House) this);
		}
		
		#endregion Clone
	}
	
}
