// Automatically generated by Model#
// Remove the above line before editing this file and it won't be changed by Model#

using System;
using System.ComponentModel;
using org.pescuma.ModelSharp.Lib;
using System.Runtime.Serialization;
using System.Diagnostics;

namespace examples.config1
{

	[DataContract(Name = "Line", Namespace = "data")]
	public class Line : BaseLine
	{
		public Line()
		: base()
		{
		}
		
		public Line(Line other)
		: base(other)
		{
		}
		
	}
	
}
