// Automatically generated by Model#
// Remove the above line before editing this file and it won't be changed by Model#

using System.Collections.Generic;
using System;
using System.ComponentModel;
using org.pescuma.ModelSharp.Lib;
using System.Runtime.Serialization;
using System.Diagnostics;

namespace examples.extends
{

	[DataContract(Name = "C")]
	public class C : BaseC
	{
		public C()
		: base()
		{
		}
		
		public C(C other)
		: base(other)
		{
		}
		
	}
	
}
