// Automatically generated by Model#
// DO NOT EDIT THIS FILE

using System.Runtime.Serialization;
using System.Diagnostics;
using System;

namespace examples.immutable
{

	public class PointBuilder
	{
		private double _x;
		private double _y = 2;
		
		public virtual PointBuilder Set(Point other)
		{
			SetX(other.X);
			SetY(other.Y);
			return this;
		}
		
		public virtual PointBuilder SetX(double x)
		{
			_x = x;
			return this;
		}
		
		public virtual PointBuilder SetY(double y)
		{
			_y = y;
			return this;
		}
		
		public virtual Point Build()
		{
			return new Point(_x, _y);
		}
	}
	
}
