// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.pescuma.ModelSharp.Core.templates
{
    using org.pescuma.ModelSharp.Core.model;
    using System;
    
    
    #line 1 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class MutableClass : TemplateUtils
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("// Automatically generated by Model#\r\n// DO NOT EDIT THIS FILE\r\n\r\n");
            
            #line 8 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("CreateUsing", it.Using); 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 10 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Package != null) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 11 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Package));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\r\n");
            
            #line 14 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 15 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Documentation != null) { 
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 17 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Documentation));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n");
            
            #line 19 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 20 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Annotation", it.Annotations); 
            
            #line default
            #line hidden
            
            #line 21 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Annotation", it.BaseOnlyAnnotations); 
            
            #line default
            #line hidden
            this.Write("\tpublic abstract class ");
            
            #line 22 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.ExtendsOrImplements.Count > 0) { 
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 22 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach(it.ExtendsOrImplements, separator: ", "); 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t#region Field Name Defines\r\n\r\n");
            
            #line 26 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.BaseClass.IsGenerated) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic new class PROPERTIES : ");
            
            #line 27 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Extends));
            
            #line default
            #line hidden
            this.Write(".PROPERTIES\r\n");
            
            #line 28 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic class PROPERTIES\r\n");
            
            #line 30 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t{\r\n");
            
            #line 32 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Define", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t#endregion\r\n\r\n\t\t#region Constructors\r\n\r\n\t\tpublic ");
            
            #line 39 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 39 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Param", it.ContructorArguments, separator: ", "); 
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 41 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotNullIfRequired", it.ContructorArguments); 
            
            #line default
            #line hidden
            
            #line 42 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableInitField", it.NonComputedProperties); 
            
            #line default
            #line hidden
            
            #line 43 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableParamToField", it.ContructorArguments); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 46 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Cloneable) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 47 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 47 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write(" other)\r\n");
            
            #line 48 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
		if (it.Extends != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t: base(other)\r\n");
            
            #line 50 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t{\r\n");
            
            #line 52 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableOtherToField", it.NonComputedProperties); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 55 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n\r\n");
            
            #line 58 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Property", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual void CopyFrom(");
            
            #line 59 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(" other)\r\n\t\t{\r\n");
            
            #line 61 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.BaseClass.HasCopyFrom) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tbase.CopyFrom(other);\r\n");
            
            #line 63 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 64 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableOtherCopyToField", it.NonComputedProperties); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t#region Property Notification\r\n\r\n");
            
            #line 69 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (!it.BaseClass.HasPropertyChanging) { 
            
            #line default
            #line hidden
            this.Write(@"		public event PropertyChangingEventHandler PropertyChanging;

		protected virtual void NotifyPropertyChanging(string propertyName)
		{
			PropertyChangingEventHandler handler = PropertyChanging;
			if (handler != null)
				handler(this, new PropertyChangingEventArgs(propertyName));
");
            
            #line 77 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanging", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 80 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } else if (it.PropertiesWithDependencies.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual void NotifyPropertyChanging(string propertyName)\r\n\t\t{\r\n\t\t\tbas" +
                    "e.NotifyPropertyChanging(propertyName);\r\n");
            
            #line 84 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanging", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 87 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 88 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (!it.BaseClass.HasChildPropertyChanging) { 
            
            #line default
            #line hidden
            this.Write(@"		public event ChildPropertyChangingEventHandler ChildPropertyChanging;
		
		protected virtual void NotifyChildPropertyChanging(string propertyName, object sender, PropertyChangingEventArgs e)
		{
			ChildPropertyChangingEventHandler handler = ChildPropertyChanging;
			if (handler != null)
				handler(sender, new ChildPropertyChangingEventArgs(this, propertyName, e));
");
            
            #line 96 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanging", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 99 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } else if (it.PropertiesWithDependencies.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual void NotifyChildPropertyChanging(string propertyName, object " +
                    "sender, PropertyChangingEventArgs e)\r\n\t\t{\r\n\t\t\tbase.NotifyChildPropertyChanging(p" +
                    "ropertyName, sender, e);\r\n");
            
            #line 103 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanging", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 106 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 107 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (!it.BaseClass.HasPropertyChanged) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic event PropertyChangedEventHandler PropertyChanged;\r\n\r\n\t\tprotected virtua" +
                    "l void NotifyPropertyChanged(string propertyName)\r\n\t\t{\r\n");
            
            #line 112 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("InvalidateComputedDependenciesCache", it.PropertiesWithCachedComputedDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t\tPropertyChangedEventHandler handler = PropertyChanged;\r\n\t\t\tif (handler != null" +
                    ")\r\n\t\t\t\thandler(this, new PropertyChangedEventArgs(propertyName));\r\n");
            
            #line 116 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanged", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 119 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } else if (it.PropertiesWithDependencies.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual void NotifyPropertyChanged(string propertyName)\r\n\t\t{\r\n");
            
            #line 122 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("InvalidateComputedDependenciesCache", it.PropertiesWithCachedComputedDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t\tbase.NotifyPropertyChanged(propertyName);\r\n");
            
            #line 124 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanged", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 127 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 128 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (!it.BaseClass.HasChildPropertyChanged) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic event ChildPropertyChangedEventHandler ChildPropertyChanged;\r\n\t\t\r\n\t\tprot" +
                    "ected virtual void NotifyChildPropertyChanged(string propertyName, object sender" +
                    ", PropertyChangedEventArgs e)\r\n\t\t{\r\n");
            
            #line 133 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("InvalidateComputedDependenciesCache", it.PropertiesWithCachedComputedDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t\tChildPropertyChangedEventHandler handler = ChildPropertyChanged;\r\n\t\t\tif (handl" +
                    "er != null)\r\n\t\t\t\thandler(sender, new ChildPropertyChangedEventArgs(this, propert" +
                    "yName, e));\r\n");
            
            #line 137 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanged", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 140 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } else if (it.PropertiesWithDependencies.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual void NotifyChildPropertyChanged(string propertyName, object s" +
                    "ender, PropertyChangedEventArgs e)\r\n\t\t{\r\n");
            
            #line 143 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("InvalidateComputedDependenciesCache", it.PropertiesWithCachedComputedDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t\tbase.NotifyChildPropertyChanged(propertyName, sender, e);\r\n");
            
            #line 145 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotifyDependenciesChanged", it.PropertiesWithDependencies); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 148 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 150 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Cloneable) { 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t#region Clone\r\n\r\n\t\tpublic new ");
            
            #line 154 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(" Clone()\r\n\t\t{\r\n\t\t\treturn (");
            
            #line 156 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(") ((ICloneable) this).Clone();\r\n\t\t}\r\n\r\n\t\tobject ICloneable.Clone()\r\n\t\t{\r\n\t\t\tretur" +
                    "n new ");
            
            #line 161 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("((");
            
            #line 161 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(") this);\r\n\t\t}\r\n\r\n\t\t#endregion\r\n");
            
            #line 165 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 167 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Package != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            
            #line 170 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "X:\c#\modelsharp\Core\templates\MutableClass.tt"

private global::org.pescuma.ModelSharp.Core.model.TypeInfo _itField;

/// <summary>
/// Access the it parameter of the template.
/// </summary>
private global::org.pescuma.ModelSharp.Core.model.TypeInfo it
{
    get
    {
        return this._itField;
    }
}

private string _classField;

/// <summary>
/// Access the class parameter of the template.
/// </summary>
private string @class
{
    get
    {
        return this._classField;
    }
}


public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool itValueAcquired = false;
if (this.Session.ContainsKey("it"))
{
    if ((typeof(global::org.pescuma.ModelSharp.Core.model.TypeInfo).IsAssignableFrom(this.Session["it"].GetType()) == false))
    {
        this.Error("The type \'org.pescuma.ModelSharp.Core.model.TypeInfo\' of the parameter \'it\' did n" +
                "ot match the type of the data passed to the template.");
    }
    else
    {
        this._itField = ((global::org.pescuma.ModelSharp.Core.model.TypeInfo)(this.Session["it"]));
        itValueAcquired = true;
    }
}
if ((itValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("it");
    if ((data != null))
    {
        if ((typeof(global::org.pescuma.ModelSharp.Core.model.TypeInfo).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'org.pescuma.ModelSharp.Core.model.TypeInfo\' of the parameter \'it\' did n" +
                    "ot match the type of the data passed to the template.");
        }
        else
        {
            this._itField = ((global::org.pescuma.ModelSharp.Core.model.TypeInfo)(data));
        }
    }
}
bool classValueAcquired = false;
if (this.Session.ContainsKey("class"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["class"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'class\' did not match the type of the d" +
                "ata passed to the template.");
    }
    else
    {
        this._classField = ((string)(this.Session["class"]));
        classValueAcquired = true;
    }
}
if ((classValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("class");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'class\' did not match the type of the d" +
                    "ata passed to the template.");
        }
        else
        {
            this._classField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
