// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.pescuma.ModelSharp.Core.templates
{
    using org.pescuma.ModelSharp.Core.model;
    using System;
    
    
    #line 1 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class MutableClass : TemplateUtils
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("// Automatically generated by Model#\r\n// DO NOT EDIT THIS FILE\r\n\r\n");
            
            #line 8 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("CreateUsing", it.Using); 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 10 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Package != null) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 11 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Package));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\r\n");
            
            #line 14 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            
            #line 15 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Annotation", it.Annotations); 
            
            #line default
            #line hidden
            this.Write("\tpublic abstract class ");
            
            #line 16 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Implements.Count > 0) { 
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 16 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach(it.Implements, separator: ", "); 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 16 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t#region Field Name Defines\r\n\r\n\t\tpublic class PROPERTIES\r\n\t\t{\r\n");
            
            #line 23 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Define", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t#endregion\r\n\r\n\t\t#region Constructors\r\n\r\n\t\tpublic ");
            
            #line 30 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 30 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Param", it.ContructorArguments, separator: ", "); 
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 32 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("NotNullIfRequired", it.ContructorArguments); 
            
            #line default
            #line hidden
            
            #line 33 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableInitField", it.Properties); 
            
            #line default
            #line hidden
            
            #line 34 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableParamToField", it.ContructorArguments); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic ");
            
            #line 37 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 37 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.ImplementationName));
            
            #line default
            #line hidden
            this.Write(" other)\r\n\t\t{\r\n");
            
            #line 39 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableOtherToField", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t#endregion\r\n\r\n");
            
            #line 44 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("Property", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t#region Get/Set by name and CopyFrom\r\n\t\t\r\n\t\tpublic object GetField(string field" +
                    "Name)\r\n\t\t{\r\n\t\t\tswitch (fieldName)\r\n\t\t\t{\r\n");
            
            #line 51 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("SwitchGetter", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\r\n\t\t\tthrow new ArgumentException(\"No gettable field named \" + fieldName);\r\n" +
                    "\t\t}\r\n\r\n\t\tpublic void SetField(string fieldName, object value)\r\n\t\t{\r\n");
            
            #line 59 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.HasSettableProperties) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tswitch (fieldName)\r\n\t\t\t{\r\n");
            
            #line 62 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("SwitchSetter", it.Properties); 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\r\n");
            
            #line 65 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tthrow new ArgumentException(\"No settable field named \" + fieldName);\r\n\t\t}\r\n\r\n\t" +
                    "\tpublic void CopyFrom(");
            
            #line 69 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(" other)\r\n\t\t{\r\n");
            
            #line 71 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 ForEach("MutableOtherCopyToField", it.Properties); 
            
            #line default
            #line hidden
            this.Write(@"		}

		#endregion

		#region Property Notification

		public event PropertyChangingEventHandler PropertyChanging;
		public event ChildPropertyChangingEventHandler ChildPropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;
		public event ChildPropertyChangedEventHandler ChildPropertyChanged;

		protected void NotifyPropertyChanging(string propertyName)
		{
			PropertyChangingEventHandler handler = PropertyChanging;
			if (handler != null)
				handler(this, new PropertyChangingEventArgs(propertyName));
		}
		
		protected void NotifyChildPropertyChanging(string propertyName, object sender, PropertyChangingEventArgs e)
		{
			ChildPropertyChangingEventHandler handler = ChildPropertyChanging;
			if (handler != null)
				handler(sender, new ChildPropertyChangingEventArgs(this, propertyName, e));
		}

		protected void NotifyPropertyChanged(string propertyName)
		{
			PropertyChangedEventHandler handler = PropertyChanged;
			if (handler != null)
				handler(this, new PropertyChangedEventArgs(propertyName));
		}
		
		protected void NotifyChildPropertyChanged(string propertyName, object sender, PropertyChangedEventArgs e)
		{
			ChildPropertyChangedEventHandler handler = ChildPropertyChanged;
			if (handler != null)
				handler(sender, new ChildPropertyChangedEventArgs(this, propertyName, e));
		}

		#endregion
		
		#region Clone

		public ");
            
            #line 116 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(" Clone()\r\n\t\t{\r\n\t\t\treturn (");
            
            #line 118 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(") ((ICloneable) this).Clone();\r\n\t\t}\r\n\r\n\t\tobject ICloneable.Clone()\r\n\t\t{\r\n\t\t\tretur" +
                    "n new ");
            
            #line 123 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("((");
            
            #line 123 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(") this);\r\n\t\t}\r\n\r\n\t\t#endregion\r\n\t}\r\n");
            
            #line 128 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 if (it.Package != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            
            #line 131 "X:\c#\modelsharp\Core\templates\MutableClass.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "X:\c#\modelsharp\Core\templates\MutableClass.tt"

private global::org.pescuma.ModelSharp.Core.model.TypeInfo _itField;

/// <summary>
/// Access the it parameter of the template.
/// </summary>
private global::org.pescuma.ModelSharp.Core.model.TypeInfo it
{
    get
    {
        return this._itField;
    }
}

private string _classField;

/// <summary>
/// Access the class parameter of the template.
/// </summary>
private string @class
{
    get
    {
        return this._classField;
    }
}


public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool itValueAcquired = false;
if (this.Session.ContainsKey("it"))
{
    if ((typeof(global::org.pescuma.ModelSharp.Core.model.TypeInfo).IsAssignableFrom(this.Session["it"].GetType()) == false))
    {
        this.Error("The type \'org.pescuma.ModelSharp.Core.model.TypeInfo\' of the parameter \'it\' did n" +
                "ot match the type of the data passed to the template.");
    }
    else
    {
        this._itField = ((global::org.pescuma.ModelSharp.Core.model.TypeInfo)(this.Session["it"]));
        itValueAcquired = true;
    }
}
if ((itValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("it");
    if ((data != null))
    {
        if ((typeof(global::org.pescuma.ModelSharp.Core.model.TypeInfo).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'org.pescuma.ModelSharp.Core.model.TypeInfo\' of the parameter \'it\' did n" +
                    "ot match the type of the data passed to the template.");
        }
        else
        {
            this._itField = ((global::org.pescuma.ModelSharp.Core.model.TypeInfo)(data));
        }
    }
}
bool classValueAcquired = false;
if (this.Session.ContainsKey("class"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["class"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'class\' did not match the type of the d" +
                "ata passed to the template.");
    }
    else
    {
        this._classField = ((string)(this.Session["class"]));
        classValueAcquired = true;
    }
}
if ((classValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("class");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'class\' did not match the type of the d" +
                    "ata passed to the template.");
        }
        else
        {
            this._classField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
