// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.pescuma.ModelSharp.Core.templates
{
    using org.pescuma.ModelSharp.Core.model;
    using System;
    
    
    #line 1 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class SimpleProperty : TemplateUtils
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            
            #line 4 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 ForEach("Annotation", it.FieldAnnotations); 
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 5 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.ReadOnly) { 
            
            #line default
            #line hidden
            this.Write("readonly ");
            
            #line 5 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 5 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 5 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 7 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Documentation != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// ");
            
            #line 9 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Documentation));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// </summary>\r\n");
            
            #line 11 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 12 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 ForEach("Annotation", it.Annotations); 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.GetterVisibility != null) { 
            
            #line default
            #line hidden
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.GetterVisibility));
            
            #line default
            #line hidden
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("public");
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t{\r\n");
            
            #line 15 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Getter != null) { 
            
            #line default
            #line hidden
            
            #line 16 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.PropGetAnnotations); 
            
            #line default
            #line hidden
            this.Write("\t\t\tget{ return ");
            
            #line 17 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Getter.Name));
            
            #line default
            #line hidden
            this.Write("(); }\r\n");
            
            #line 18 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Setter != null) { 
            
            #line default
            #line hidden
            
            #line 20 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.PropSetAnnotations); 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 21 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.SetterVisibility != null) { 
            
            #line default
            #line hidden
            
            #line 21 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.SetterVisibility));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            this.Write("set{ ");
            
            #line 21 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Setter.Name));
            
            #line default
            #line hidden
            this.Write("(value); }\r\n");
            
            #line 22 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 24 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.LazyInitializer != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.LazyInitializer.Annotations); 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual ");
            
            #line 27 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.LazyInitializer.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.LazyInitializer.Name));
            
            #line default
            #line hidden
            this.Write("() \r\n\t\t{\r\n\t\t\tif (this.");
            
            #line 29 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t\treturn;\r\n\r\n");
            
            #line 32 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		var val = (it.DefaultValue != null ? it.DefaultValue : "new " + it.TypeName + "()"); 
            
            #line default
            #line hidden
            
            #line 33 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.Validator != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 34 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 34 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 34 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 35 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Validator.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 35 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tthis.");
            
            #line 36 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 36 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 37 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 38 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 38 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 39 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            
            #line 40 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.CanListenTo) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tAdd");
            
            #line 41 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("Listeners(this.");
            
            #line 41 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 42 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 44 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 45 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Getter != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.Getter.Annotations); 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual ");
            
            #line 48 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Getter.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Getter.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n");
            
            #line 50 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.LazyInitializer != null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 51 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.LazyInitializer.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 52 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn this.");
            
            #line 53 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n");
            
            #line 55 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 56 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Validator != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 58 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.Validator.Annotations); 
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 59 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Validator.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 59 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Validator.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 59 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Validator.Parameters[0]));
            
            #line default
            #line hidden
            this.Write(" value)\r\n\t\t{\r\n#pragma warning disable 219\r\n\t\t\tvar property = PROPERTIES.");
            
            #line 62 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(";\r\n#pragma warning restore 219\r\n");
            
            #line 64 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("PropertyValidate", it.Validations); 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 66 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } 
            
            #line default
            #line hidden
            
            #line 67 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.Setter != null) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		ForEach("Annotation", it.Setter.Annotations); 
            
            #line default
            #line hidden
            this.Write("\t\tprotected virtual ");
            
            #line 70 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Setter.TypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Setter.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 70 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Setter.Parameters[0]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(") \r\n\t\t{\r\n");
            
            #line 72 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.Precision > 0) { 
            
            #line default
            #line hidden
            
            #line 73 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
			if (it.IsNullable) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (this.");
            
            #line 74 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" == null && ");
            
            #line 74 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n\t\t\t\treturn false;\r\n\t\t\tif (this.");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" != null && ");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(" != null && Math.Abs((");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.NonNullableTypeName));
            
            #line default
            #line hidden
            this.Write(") this.");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" - (");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.NonNullableTypeName));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(") < ");
            
            #line 76 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Precision));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\treturn false;\r\n");
            
            #line 78 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
			} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (Math.Abs(this.");
            
            #line 79 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" - ");
            
            #line 79 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(") < ");
            
            #line 79 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Precision));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\treturn false;\r\n");
            
            #line 81 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
			} 
            
            #line default
            #line hidden
            
            #line 82 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (this.");
            
            #line 83 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 83 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\treturn false;\r\n");
            
            #line 85 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            
            #line 86 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		Include("ValidateIfRequired", it, "param", it.VarName); 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tNotifyPropertyChanging(PROPERTIES.");
            
            #line 88 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 90 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.CanListenTo) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tRemove");
            
            #line 91 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("Listeners(this.");
            
            #line 91 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 93 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 94 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 94 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.VarName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 96 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.CanListenTo) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tAdd");
            
            #line 97 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("Listeners(this.");
            
            #line 97 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.FieldName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 99 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} 
            
            #line default
            #line hidden
            this.Write("\t\t\tNotifyPropertyChanged(PROPERTIES.");
            
            #line 100 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\t\treturn true;\r\n\t\t}\r\n");
            
            #line 104 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		if (it.CanListenTo) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate void Remove");
            
            #line 106 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("Listeners(object child)\r\n\t\t{\r\n\t\t\tif (child == null)\r\n\t\t\t\treturn;\r\n\r\n\t\t\tvar notify" +
                    "PropertyChanging = child as INotifyPropertyChanging;\r\n\t\t\tif (notifyPropertyChang" +
                    "ing != null)\r\n\t\t\t\tnotifyPropertyChanging.PropertyChanging -= ");
            
            #line 113 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangingEventHandler;\r\n\r\n\t\t\tvar notifyChildPropertyChanging = child as IN" +
                    "otifyChildPropertyChanging;\r\n\t\t\tif (notifyChildPropertyChanging != null)\r\n\t\t\t\tno" +
                    "tifyChildPropertyChanging.ChildPropertyChanging -= ");
            
            #line 117 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangingEventHandler;\r\n\r\n\t\t\tvar notifyPropertyChanged = child as INo" +
                    "tifyPropertyChanged;\r\n\t\t\tif (notifyPropertyChanged != null)\r\n\t\t\t\tnotifyPropertyC" +
                    "hanged.PropertyChanged -= ");
            
            #line 121 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangedEventHandler;\r\n\r\n\t\t\tvar notifyChildPropertyChanged = child as INot" +
                    "ifyChildPropertyChanged;\r\n\t\t\tif (notifyChildPropertyChanged != null)\r\n\t\t\t\tnotify" +
                    "ChildPropertyChanged.ChildPropertyChanged -= ");
            
            #line 125 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangedEventHandler;\r\n\t\t}\r\n");
            
            #line 127 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
		} // if (it.CanListenTo) 
            
            #line default
            #line hidden
            
            #line 128 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } // if (it.Setter) 
            
            #line default
            #line hidden
            
            #line 129 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 if (it.CanListenTo) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate void Add");
            
            #line 131 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("Listeners(object child)\r\n\t\t{\r\n\t\t\tif (child == null)\r\n\t\t\t\treturn;\r\n\r\n\t\t\tvar notify" +
                    "PropertyChanging = child as INotifyPropertyChanging;\r\n\t\t\tif (notifyPropertyChang" +
                    "ing != null)\r\n\t\t\t\tnotifyPropertyChanging.PropertyChanging += ");
            
            #line 138 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangingEventHandler;\r\n\r\n\t\t\tvar notifyChildPropertyChanging = child as IN" +
                    "otifyChildPropertyChanging;\r\n\t\t\tif (notifyChildPropertyChanging != null)\r\n\t\t\t\tno" +
                    "tifyChildPropertyChanging.ChildPropertyChanging += ");
            
            #line 142 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangingEventHandler;\r\n\r\n\t\t\tvar notifyPropertyChanged = child as INo" +
                    "tifyPropertyChanged;\r\n\t\t\tif (notifyPropertyChanged != null)\r\n\t\t\t\tnotifyPropertyC" +
                    "hanged.PropertyChanged += ");
            
            #line 146 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangedEventHandler;\r\n\r\n\t\t\tvar notifyChildPropertyChanged = child as INot" +
                    "ifyChildPropertyChanged;\r\n\t\t\tif (notifyChildPropertyChanged != null)\r\n\t\t\t\tnotify" +
                    "ChildPropertyChanged.ChildPropertyChanged += ");
            
            #line 150 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangedEventHandler;\r\n\t\t}\r\n\r\n\t\tprivate void ");
            
            #line 153 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangingEventHandler(object sender, PropertyChangingEventArgs e)\r\n\t\t{\r\n\t\t" +
                    "\tNotifyChildPropertyChanging(PROPERTIES.");
            
            #line 155 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(", sender, e);\r\n\t\t}\r\n\r\n\t\tprivate void ");
            
            #line 158 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangingEventHandler(object sender, ChildPropertyChangingEventArgs e" +
                    ")\r\n\t\t{\r\n\t\t\tNotifyChildPropertyChanging(PROPERTIES.");
            
            #line 160 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(", sender, e);\r\n\t\t}\r\n\r\n\t\tprivate void ");
            
            #line 163 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("PropertyChangedEventHandler(object sender, PropertyChangedEventArgs e)\r\n\t\t{\r\n\t\t\tN" +
                    "otifyChildPropertyChanged(PROPERTIES.");
            
            #line 165 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(", sender, e);\r\n\t\t}\r\n\r\n\t\tprivate void ");
            
            #line 168 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.Name));
            
            #line default
            #line hidden
            this.Write("ChildPropertyChangedEventHandler(object sender, ChildPropertyChangedEventArgs e)\r" +
                    "\n\t\t{\r\n\t\t\tNotifyChildPropertyChanged(PROPERTIES.");
            
            #line 170 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(it.DefineName));
            
            #line default
            #line hidden
            this.Write(", sender, e);\r\n\t\t}\r\n");
            
            #line 172 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"
 } // if (it.CanListenTo) 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "X:\c#\modelsharp\Core\templates\SimpleProperty.tt"

private global::org.pescuma.ModelSharp.Core.model.PropertyInfo _itField;

/// <summary>
/// Access the it parameter of the template.
/// </summary>
private global::org.pescuma.ModelSharp.Core.model.PropertyInfo it
{
    get
    {
        return this._itField;
    }
}


public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool itValueAcquired = false;
if (this.Session.ContainsKey("it"))
{
    if ((typeof(global::org.pescuma.ModelSharp.Core.model.PropertyInfo).IsAssignableFrom(this.Session["it"].GetType()) == false))
    {
        this.Error("The type \'org.pescuma.ModelSharp.Core.model.PropertyInfo\' of the parameter \'it\' d" +
                "id not match the type of the data passed to the template.");
    }
    else
    {
        this._itField = ((global::org.pescuma.ModelSharp.Core.model.PropertyInfo)(this.Session["it"]));
        itValueAcquired = true;
    }
}
if ((itValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("it");
    if ((data != null))
    {
        if ((typeof(global::org.pescuma.ModelSharp.Core.model.PropertyInfo).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'org.pescuma.ModelSharp.Core.model.PropertyInfo\' of the parameter \'it\' d" +
                    "id not match the type of the data passed to the template.");
        }
        else
        {
            this._itField = ((global::org.pescuma.ModelSharp.Core.model.PropertyInfo)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
